name: Deploy Strudel to GitHub Pages

on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  # Allow manual trigger from Actions tab
  workflow_dispatch:

# Permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history if needed for monorepo
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Node 20 for Astro 5.15+ and Strudel
          cache: 'pnpm'  # Cache pnpm for monorepo speed

      - name: Install dependencies with pnpm
        # Run in root for monorepo (pnpm-workspace.yaml)
        run: pnpm install --frozen-lockfile

      - name: Build Strudel site
        # Build from website/ directory
        run: cd website && pnpm build
        # Optional env for Strudel config
        env:
          PUBLIC_BASE_PATH: '/strudel/'  # If needed for subpath

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/dist  # Strudel build output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
